### ISSUE TITLE
Local explorer models do not update when you update a saved query

### ISSUE THREAD

**Issue by josephwegner** [keen/explorer#68]
It seems that when you try to update an attribute of a saved query, the update gets sent to the API, but the local explorer model does not get updated.

This propagates in the UI as hitting the "Update" button seems to revert your changes. However, upon refresh, your changes will be there.

**Comment by aroc** [comment]
Turns out this is a bug at the API level. The saved queries resource returns the old query definition rather than the new updated one, and explorer merges the API response into the model that was updated, so it has it's attributes replaced with old values. It happens intermittently and is tough to track down apparently.

**Comment by joannecheng** [comment]
This is an API level bug, closing
