### ISSUE TITLE
Filters - 'not in'

### ISSUE THREAD

**Issue by andygnewman** [keen/explorer#91]
I'm working to exclude a small number of outliers from a dataset.

The most preferable way to do this would be a a 'not in' filter against an array of values.

The documentation is a little ambiguous on whether this is possible; 
'in: Whether or not the property value is in a given set of values. The value passed in must be a JSON array of values. Example: [1,2,4,5].'

Would be great to have this as an enhancement.

**Comment by nemo** [comment]
:+1: – there's already list of values (Strings or Numbers) support for an "in" filter. Not in would be great!

**Comment by aroc** [comment]
The request been passed along to our team. it's definitely not the first time we've heard this request. Because this would be a core Keen API feature, not an Explorer feature. Explorer makes use of Keen APIs but doesn't do any querying or filters of the data directly. As such I'm gonna close this issue out.

**Comment by robertvanhoesel** [comment]
@aroc is there any update on this? Would come in very handy.

**Comment by aroc** [comment]
@robertvanhoesel No updates to share right now. We don't have `not in` filters in the API feature roadmap at this time.
